export * as mainAPI from './main';
export * as favoritesAPI from './favorites';
export * as basketAPI from './basket';
export * as callbackAPI from './callback';
export * as catalogAPI from './catalog';
export * as productsAPI from './products';
export * as userAPI from './user';
export * as categoriesAPI from './categories';
export * as ordersAPI from './orders';